name: Convert MKV to MP4 and Upload to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Verify ffmpeg Installation
      run: ffmpeg -version

    - name: Run Conversion and Upload Script
      run: |
        echo "Starting the conversion and upload process..."
        python3 main.py
