name: Install N_m3u8DL-RE on Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download N_m3u8DL-RE
        run: wget https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.3.0-beta/N_m3u8DL-RE_v0.3.0-beta_linux-x64_20241203.tar.gz

      - name: Extract N_m3u8DL-RE
        run: tar -xzf N_m3u8DL-RE_v0.3.0-beta_linux-x64_20241203.tar.gz

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:mc3man/mpv-tests
          sudo apt-get install -y libmpv2

      - name: Set up N_m3u8DL-RE
        run: |
          sudo mv N_m3u8DL-RE /usr/local/bin/
          sudo chmod +x /usr/local/bin/N_m3u8DL-RE

      - name: Install Python
        run: sudo apt-get install -y python3 python3-pip

      - name: Install Python requirements
        run: pip3 install -r requirements.txt

      - name: Run Python script
        run: python3 main.py
